name: Unity CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: webbertakken/unity-actions@v2
      with:
        unityVersion: 2022.3.7f1  # Specify the Unity version you are using

    - name: Build Unity project
      run: |
        unity -batchmode -quit -projectPath $GITHUB_WORKSPACE -executeMethod Prototype.Build
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}


    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Artifact
        path: Builds
